# Generated by Django 4.0 on 2021-12-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharesName',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('temper_tonghuashun', models.IntegerField(default=0)),
                ('temper_dongfangcaifu', models.IntegerField(default=0)),
                ('area_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'mc_shares_name',
            },
        ),
    ]
