# Generated by Django 4.0 on 2021-12-19 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharesKdj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k', models.IntegerField(default=0)),
                ('d', models.IntegerField(default=0)),
                ('j', models.IntegerField(default=0)),
                ('cycle_type', models.IntegerField(default=0, help_text='1.9,3,3')),
                ('date_as', models.DateField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shares.sharesname')),
            ],
            options={
                'db_table': 'mc_shares_kdj',
            },
        ),
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('p_min', models.IntegerField(default=0)),
                ('p_max', models.IntegerField(default=0)),
                ('p_start', models.IntegerField(default=0)),
                ('p_end', models.IntegerField(default=0)),
                ('p_range', models.IntegerField(default=0)),
                ('buy_count', models.IntegerField(default=0)),
                ('buy_sum', models.IntegerField(default=0)),
                ('date_as', models.DateField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shares.sharesname')),
            ],
            options={
                'db_table': 'mc_shares',
            },
        ),
    ]
