# Generated by Django 4.0 on 2021-12-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_shareskdj_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharesname',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
