# Generated by Django 4.0 on 2021-12-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0003_sharesname_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareskdj',
            name='d',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shareskdj',
            name='j',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shareskdj',
            name='k',
            field=models.FloatField(default=0),
        ),
    ]
