# Generated by Django 4.0 on 2021-12-23 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0004_alter_shareskdj_d_alter_shareskdj_j_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharesBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remain_avoid_cycle', models.IntegerField(default=0, help_text='剩余回避天数')),
                ('avoid_cycle', models.FloatField(default=0, help_text='回避天数')),
                ('avoid_reason', models.CharField(help_text='原因', max_length=20)),
                ('date_as', models.DateField()),
            ],
            options={
                'db_table': 'mc_shares_ban',
            },
        ),
    ]
