# Generated by Django 4.0 on 2021-12-25 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0005_sharesban'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharesban',
            name='code',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shares.sharesname'),
        ),
    ]
