# Generated by Django 4.0 on 2021-12-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0008_shareskdjcompute_intersection_pre_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareskdjcomputedetail',
            name='buy_date_as',
            field=models.DateField(help_text='买点日期'),
        ),
        migrations.AlterField(
            model_name='shareskdjcomputedetail',
            name='buy_date_as_end',
            field=models.DateField(help_text='买点结束日期'),
        ),
    ]
