# Generated by Django 4.0 on 2022-01-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0009_alter_shareskdjcomputedetail_buy_date_as_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharesname',
            name='code_type',
            field=models.IntegerField(default=0, help_text='1股票，2行业板块'),
        ),
    ]
