# Generated by Django 4.0 on 2022-01-01 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0010_sharesname_code_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharesIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shares.sharesname')),
                ('industry_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_code_id', to='shares.sharesname')),
            ],
            options={
                'db_table': 'mc_shares_industry',
            },
        ),
    ]
