# Generated by Django 4.0 on 2022-01-01 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0011_sharesindustry'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sharesindustry',
            table='mc_shares_join_industry',
        ),
    ]
