# Generated by Django 4.0 on 2022-01-01 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0011_sharesjoinindustry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharesIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_min', models.IntegerField(default=0)),
                ('p_max', models.IntegerField(default=0)),
                ('p_start', models.IntegerField(default=0)),
                ('p_end', models.IntegerField(default=0)),
                ('date_as', models.DateField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shares.sharesname')),
            ],
            options={
                'db_table': 'mc_shares_industry',
            },
        ),
    ]
