# Generated by Django 4.0 on 2022-01-14 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0014_sharesindustrykdj'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharesMacd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macd', models.FloatField(default=0)),
                ('diff', models.FloatField(default=0)),
                ('dea', models.FloatField(default=0)),
                ('cycle_type', models.IntegerField(default=0, help_text='1.9,3,3')),
                ('date_as', models.DateField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shares.sharesname')),
            ],
            options={
                'db_table': 'mc_shares_macd',
            },
        ),
    ]
