# Generated by Django 4.0 on 2022-02-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0015_sharesmacd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharesmacd',
            name='cycle_type',
            field=models.IntegerField(default=0, help_text='1.26,12,9'),
        ),
    ]
