# Generated by Django 4.0 on 2022-02-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0016_alter_sharesmacd_cycle_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutruesHot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='同花顺热门商品编号', max_length=20)),
                ('name', models.CharField(help_text='名字', max_length=30)),
                ('industry', models.CharField(help_text='行业', max_length=30)),
                ('today_zdf', models.FloatField(default=0, help_text='今日涨幅')),
                ('five_zdf', models.FloatField(default=0, help_text='5日涨幅')),
                ('ten_zdf', models.FloatField(default=0, help_text='10日涨幅')),
                ('twenty_zdf', models.FloatField(default=0, help_text='20日涨幅')),
                ('sixty_zdf', models.FloatField(default=0, help_text='60日涨幅')),
            ],
            options={
                'db_table': 'mc_futrues_hot',
            },
        ),
        migrations.CreateModel(
            name='FutruesJoinShares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='股票编码', max_length=20)),
                ('futrues_id', models.CharField(help_text='futrues_hot_id', max_length=20)),
            ],
            options={
                'db_table': 'mc_futrues_join_shares',
            },
        ),
    ]
