# Generated by Django 4.0 on 2022-04-01 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0017_futrueshot_futruesjoinshares'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharesSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('p_start', models.IntegerField(default=0)),
                ('p_end', models.IntegerField(default=0)),
                ('p_year', models.IntegerField(default=0)),
                ('p_season', models.IntegerField(default=0, help_text='1 第一季，2 第二季')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shares.sharesname')),
            ],
            options={
                'db_table': 'mc_shares_season',
            },
        ),
        migrations.CreateModel(
            name='SharesHalfYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('p_start', models.IntegerField(default=0)),
                ('p_end', models.IntegerField(default=0)),
                ('p_year', models.IntegerField(default=0)),
                ('p_year_half', models.IntegerField(default=0, help_text='1 前半年，2 后半年')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shares.sharesname')),
            ],
            options={
                'db_table': 'mc_shares_half_year',
            },
        ),
    ]
