# Generated by Django 4.0 on 2022-07-08 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0018_sharesseason_shareshalfyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharesDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_as', models.DateField()),
            ],
            options={
                'db_table': 'mc_shares_date',
            },
        ),
        migrations.AddField(
            model_name='shares',
            name='master_buy_sell',
            field=models.IntegerField(default=0, help_text='主力流出'),
        ),
        migrations.AddField(
            model_name='shares',
            name='master_buy_sum',
            field=models.IntegerField(default=0, help_text='主力流如'),
        ),
        migrations.AddField(
            model_name='sharesname',
            name='finance_up',
            field=models.IntegerField(default=1, help_text='财务，1 下降，2 上升'),
        ),
        migrations.AddField(
            model_name='sharesname',
            name='five_day',
            field=models.IntegerField(default=0, help_text='5天最低'),
        ),
        migrations.AddField(
            model_name='sharesname',
            name='four_year_day',
            field=models.IntegerField(default=0, help_text='4年最低'),
        ),
        migrations.AddField(
            model_name='sharesname',
            name='gpm',
            field=models.IntegerField(default=0, help_text='毛利率 Gross Profit Margin'),
        ),
        migrations.AddField(
            model_name='sharesname',
            name='gpm_ex',
            field=models.IntegerField(default=0, help_text='营业同比增长率'),
        ),
        migrations.AddField(
            model_name='sharesname',
            name='macd_up',
            field=models.IntegerField(default=1, help_text='macd，1 下降，2 上升'),
        ),
        migrations.AddField(
            model_name='sharesname',
            name='member_up',
            field=models.IntegerField(default=2, help_text='股东人数，1 下降，2 上升'),
        ),
        migrations.AddField(
            model_name='sharesname',
            name='npmos',
            field=models.IntegerField(default=0, help_text='净利率 Net Profit Margin on Sales'),
        ),
        migrations.AddField(
            model_name='sharesname',
            name='npmos_ex',
            field=models.IntegerField(default=0, help_text='净利润同比增长率'),
        ),
        migrations.AddField(
            model_name='sharesname',
            name='one_hundred_day',
            field=models.IntegerField(default=0, help_text='120天最低'),
        ),
        migrations.AddField(
            model_name='sharesname',
            name='pb',
            field=models.IntegerField(default=0, help_text='市净率'),
        ),
        migrations.AddField(
            model_name='sharesname',
            name='pe',
            field=models.IntegerField(default=0, help_text='市盈率(静态)'),
        ),
        migrations.AddField(
            model_name='sharesname',
            name='pe_d',
            field=models.IntegerField(default=0, help_text='市盈率(动)'),
        ),
        migrations.AddField(
            model_name='sharesname',
            name='pe_ttm',
            field=models.IntegerField(default=0, help_text='市盈率(ttm)'),
        ),
        migrations.AddField(
            model_name='sharesname',
            name='roe',
            field=models.IntegerField(default=0, help_text='加权净资产收益率'),
        ),
        migrations.AddField(
            model_name='sharesname',
            name='sixty_day',
            field=models.IntegerField(default=0, help_text='60天最低'),
        ),
        migrations.AddField(
            model_name='sharesname',
            name='twenty_day',
            field=models.IntegerField(default=0, help_text='20天最低'),
        ),
        migrations.AlterField(
            model_name='sharesname',
            name='temper_dongfangcaifu',
            field=models.IntegerField(default=0, help_text='东方财富股民看涨看跌比例'),
        ),
        migrations.AlterField(
            model_name='sharesname',
            name='temper_tonghuashun',
            field=models.IntegerField(default=0, help_text='同花顺股民看涨看跌比例'),
        ),
        migrations.CreateModel(
            name='SharesMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('p_start', models.IntegerField(default=0)),
                ('p_end', models.IntegerField(default=0)),
                ('p_year', models.IntegerField(default=0)),
                ('p_month', models.IntegerField(default=0, help_text='1 第一季，2 第二季')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shares.sharesname')),
            ],
            options={
                'db_table': 'mc_shares_month',
            },
        ),
        migrations.CreateModel(
            name='SharesMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.IntegerField(default=0, help_text='股东人数')),
                ('avg_free_shares', models.IntegerField(default=0, help_text='人均流通股(股)')),
                ('date_as', models.DateField()),
                ('info', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0, help_text='股价')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shares.sharesname')),
            ],
            options={
                'db_table': 'mc_stock_members',
            },
        ),
        migrations.CreateModel(
            name='SharesKdjHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k', models.FloatField(default=0)),
                ('d', models.FloatField(default=0)),
                ('j', models.FloatField(default=0)),
                ('cycle_type', models.IntegerField(default=0, help_text='1.9,3,3')),
                ('date_as', models.DateTimeField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shares.sharesname')),
            ],
            options={
                'db_table': 'mc_shares_kdj_hours',
            },
        ),
        migrations.CreateModel(
            name='SharesJoinBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_type', models.IntegerField(default=1, help_text='1.东方，2.同花顺')),
                ('block_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_code_id', to='shares.sharesname')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shares.sharesname')),
            ],
            options={
                'db_table': 'mc_shares_join_block',
            },
        ),
        migrations.CreateModel(
            name='SharesIndustrySeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('p_start', models.IntegerField(default=0)),
                ('p_end', models.IntegerField(default=0)),
                ('p_year', models.IntegerField(default=0)),
                ('p_season', models.IntegerField(default=0, help_text='1 第一季，2 第二季')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shares.sharesname')),
            ],
            options={
                'db_table': 'mc_shares_industry_season',
            },
        ),
        migrations.CreateModel(
            name='SharesIndustryMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('p_start', models.IntegerField(default=0)),
                ('p_end', models.IntegerField(default=0)),
                ('p_year', models.IntegerField(default=0)),
                ('p_month', models.IntegerField(default=0, help_text='1 第一季，2 第二季')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shares.sharesname')),
            ],
            options={
                'db_table': 'mc_shares_industry_month',
            },
        ),
        migrations.CreateModel(
            name='SharesIndustryMacd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macd', models.FloatField(default=0)),
                ('diff', models.FloatField(default=0)),
                ('dea', models.FloatField(default=0)),
                ('cycle_type', models.IntegerField(default=0, help_text='1.26,12,9')),
                ('date_as', models.DateField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shares.sharesname')),
            ],
            options={
                'db_table': 'mc_shares_industry_macd',
            },
        ),
        migrations.CreateModel(
            name='SharesHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('p_min', models.IntegerField(default=0)),
                ('p_max', models.IntegerField(default=0)),
                ('p_start', models.IntegerField(default=0)),
                ('p_end', models.IntegerField(default=0)),
                ('date_as', models.DateTimeField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shares.sharesname')),
            ],
            options={
                'db_table': 'mc_shares_hours',
            },
        ),
        migrations.CreateModel(
            name='SharesFH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('info', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=30)),
                ('range', models.CharField(max_length=30)),
                ('directors_date_as', models.DateField(help_text='董事会日期')),
                ('shareholder_date_as', models.DateField(help_text='股东大会预案公告日期')),
                ('implement_date_as', models.DateField(help_text='实施公告日')),
                ('register_date_as', models.DateField(help_text='A股股权登记日')),
                ('ex_date_as', models.DateField(help_text='A股除权除息日')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shares.sharesname')),
            ],
            options={
                'db_table': 'mc_shares_fh',
            },
        ),
        migrations.CreateModel(
            name='SharesDateListen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_start', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0, help_text='1.kdj-10的股票')),
                ('buy_start', models.IntegerField(default=0)),
                ('buy_pre', models.IntegerField(default=0)),
                ('buy_date_as', models.DateField(null=True)),
                ('date_as', models.DateField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shares.sharesname')),
            ],
            options={
                'db_table': 'mc_shares_date_listen',
            },
        ),
        migrations.CreateModel(
            name='SharesCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache', models.TextField(default=0, help_text='缓存')),
                ('created_at', models.DateTimeField()),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shares.sharesname')),
            ],
            options={
                'db_table': 'mc_shares_cache',
            },
        ),
        migrations.CreateModel(
            name='SharesBuys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date_as', models.DateField(null=True)),
                ('buy_start', models.IntegerField(default=0)),
                ('buy_pre', models.IntegerField(default=0)),
                ('sell_date_as', models.DateField(null=True)),
                ('sell_end', models.IntegerField(default=0)),
                ('sell_pre', models.IntegerField(default=0)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shares.sharesname')),
            ],
            options={
                'db_table': 'mc_shares_buys',
            },
        ),
    ]
