# Generated by Django 4.0 on 2022-07-08 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0019_sharesdate_shares_master_buy_sell_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pe', models.IntegerField(default=0, help_text='市盈率 * 10000')),
                ('pb', models.IntegerField(default=0, help_text='市净率 * 10000')),
                ('date_as', models.DateField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shares.sharesname')),
            ],
            options={
                'db_table': 'mc_stock_index',
            },
        ),
    ]
