# Generated by Django 4.0 on 2022-07-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0020_stockindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockindex',
            name='val',
            field=models.IntegerField(default=0, help_text='价值'),
        ),
    ]
