# Generated by Django 3.2.19 on 2023-12-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0022_auto_20231219_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharesblockgns',
            name='date_as',
            field=models.DateField(help_text='创建时间'),
        ),
        migrations.AlterField(
            model_name='shareszhangtings',
            name='continuous_zhang_ting',
            field=models.IntegerField(help_text='连续涨停次数'),
        ),
        migrations.AlterField(
            model_name='shareszhangtings',
            name='date_as',
            field=models.DateField(help_text='创建时间'),
        ),
        migrations.AlterField(
            model_name='shareszhangtings',
            name='gao_biao',
            field=models.IntegerField(help_text='高标票标记'),
        ),
        migrations.AlterField(
            model_name='shareszhangtings',
            name='liu_tong_shi_zhi',
            field=models.IntegerField(help_text='流通市值'),
        ),
        migrations.AlterField(
            model_name='shareszhangtings',
            name='n_day_n_zhang_ting',
            field=models.CharField(help_text='几天几版', max_length=30),
        ),
    ]
