# Generated by Django 3.2.19 on 2023-12-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0023_auto_20231219_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareszhangtings',
            name='continuous_zhang_ting',
            field=models.IntegerField(help_text='连续涨停天数'),
        ),
        migrations.AlterField(
            model_name='shareszhangtings',
            name='f32',
            field=models.IntegerField(help_text='9点32分钟之前涨停'),
        ),
    ]
