# Generated by Django 3.2.19 on 2023-12-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0024_auto_20231219_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareszhangtings',
            name='liu_tong_shi_zhi',
            field=models.BigIntegerField(help_text='流通市值'),
        ),
    ]
