# Generated by Django 3.2.19 on 2023-12-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0025_alter_shareszhangtings_liu_tong_shi_zhi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharesblockgns',
            name='p_end',
            field=models.FloatField(help_text='结束'),
        ),
        migrations.AlterField(
            model_name='sharesblockgns',
            name='p_max',
            field=models.FloatField(help_text='最大'),
        ),
        migrations.AlterField(
            model_name='sharesblockgns',
            name='p_min',
            field=models.FloatField(help_text='最小'),
        ),
        migrations.AlterField(
            model_name='sharesblockgns',
            name='p_start',
            field=models.FloatField(help_text='开始'),
        ),
        migrations.AlterField(
            model_name='sharesblockgns',
            name='p_zhang_die_fu',
            field=models.FloatField(help_text='涨跌幅'),
        ),
    ]
