# Generated by Django 4.0 on 2022-07-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_shares_sharesname'),
        ('polls', '0003_shareskdjcompute_shareskdjcomputedetail'),
    ]

    operations = [
    ]
